results = [{'analysis': {'emotion': {'document': {'emotion': {'anger': 0.378347,
                                                    'disgust': 0.111331,
                                                    'fear': 0.160148,
                                                    'joy': 0.009129,
                                                    'sadness': 0.497876}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.671766}}},
  'text': 'I want to kill myself right now'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.209655,
                                                    'disgust': 0.658856,
                                                    'fear': 0.112931,
                                                    'joy': 0.017063,
                                                    'sadness': 0.16738}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.474363}}},
  'text': 'Where can I buy a gun?'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.203455,
                                                    'disgust': 0.075372,
                                                    'fear': 0.10283,
                                                    'joy': 0.128933,
                                                    'sadness': 0.470818}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.539533}}},
  'text': 'Where can I get access to a roof to jump off of'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.077876,
                                                    'disgust': 0.172768,
                                                    'fear': 0.229408,
                                                    'joy': 0.049769,
                                                    'sadness': 0.531827}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.461632}}},
  'text': 'Giving away all my stuff'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.180075,
                                                    'disgust': 0.172736,
                                                    'fear': 0.055642,
                                                    'joy': 0.025639,
                                                    'sadness': 0.663172}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.694525}}},
  'text': 'My life is never going to amount to anything'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.340166,
                                                    'disgust': 0.081295,
                                                    'fear': 0.340364,
                                                    'joy': 0.00463,
                                                    'sadness': 0.399937}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.665957}}},
  'text': "I'm not getting any sleep"},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.143002,
                                                    'disgust': 0.337881,
                                                    'fear': 0.061387,
                                                    'joy': 0.264534,
                                                    'sadness': 0.141934}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.305088}}},
  'text': 'Everyone in my life is such a dick'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.162636,
                                                    'disgust': 0.00722,
                                                    'fear': 0.476618,
                                                    'joy': 0.032206,
                                                    'sadness': 0.395068}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.680665}}},
  'text': 'Just waiting for the rain to come back'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.10484,
                                                    'disgust': 0.299898,
                                                    'fear': 0.255252,
                                                    'joy': 0.022878,
                                                    'sadness': 0.448641}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.742491}}},
  'text': 'Why do I even go to school?'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.036377,
                                                    'disgust': 0.017823,
                                                    'fear': 0.127951,
                                                    'joy': 0.403481,
                                                    'sadness': 0.24551}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'neutral', 'score': 0.0}}},
  'text': 'Every day is a good day to be alone'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.124338,
                                                    'disgust': 0.086733,
                                                    'fear': 0.169043,
                                                    'joy': 0.003462,
                                                    'sadness': 0.723164}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.713431}}},
  'text': 'I wish I were dead'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.151412,
                                                    'disgust': 0.161222,
                                                    'fear': 0.11188,
                                                    'joy': 0.19615,
                                                    'sadness': 0.328214}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.615342}}},
  'text': 'Why did my parents give me life?'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.083628,
                                                    'disgust': 0.05308,
                                                    'fear': 0.423522,
                                                    'joy': 0.234417,
                                                    'sadness': 0.118584}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.485291}}},
  'text': 'Where can I get the pills?'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.231067,
                                                    'disgust': 0.06387,
                                                    'fear': 0.014921,
                                                    'joy': 0.190674,
                                                    'sadness': 0.427687}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.304336}}},
  'text': 'last love or not. Honey Cocaine is a bitch. YEAH DAT!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.182185,
                                                    'disgust': 0.050059,
                                                    'fear': 0.165321,
                                                    'joy': 0.223431,
                                                    'sadness': 0.302391}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'neutral', 'score': 0.0}}},
  'text': 'God... please forgive me.'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.036145,
                                                    'disgust': 0.017158,
                                                    'fear': 0.027305,
                                                    'joy': 0.699609,
                                                    'sadness': 0.097174}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.623194}}},
  'text': 'I love you Dad.'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.064256,
                                                    'disgust': 0.129248,
                                                    'fear': 0.323591,
                                                    'joy': 0.017338,
                                                    'sadness': 0.558452}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.436369}}},
  'text': 'Cruising in the 300 Chrysler. Wishing the world could be a little '
          "brighter. But all I can seem to find is this lighter. It's all bad "
          "y'all."},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.078831,
                                                    'disgust': 0.313954,
                                                    'fear': 0.05655,
                                                    'joy': 0.002179,
                                                    'sadness': 0.678365}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.742335}}},
  'text': 'Smoked my first pack of cigarettes today... been a long time since '
          "I've gone through heart break. It's a cold unforgiving world if I "
          'do say.'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.385925,
                                                    'disgust': 0.082584,
                                                    'fear': 0.219138,
                                                    'joy': 0.000411,
                                                    'sadness': 0.480991}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.687238}}},
  'text': "This day couldn't get any worse..."},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.662043,
                                                    'disgust': 0.117246,
                                                    'fear': 0.264558,
                                                    'joy': 0.001517,
                                                    'sadness': 0.14169}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.951616}}},
  'text': 'Just got a shitty Prius, fml'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.031689,
                                                    'disgust': 0.077986,
                                                    'fear': 0.094069,
                                                    'joy': 0.007951,
                                                    'sadness': 0.846727}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.38381}}},
  'text': 'About time he died'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.140768,
                                                    'disgust': 0.027773,
                                                    'fear': 0.012373,
                                                    'joy': 0.681406,
                                                    'sadness': 0.039687}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.792235}}},
  'text': 'Found this cool website'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.118224,
                                                    'disgust': 0.048979,
                                                    'fear': 0.434429,
                                                    'joy': 0.044908,
                                                    'sadness': 0.412155}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.256195}}},
  'text': 'Going to HSHacks'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.236069,
                                                    'disgust': 0.022346,
                                                    'fear': 0.021901,
                                                    'joy': 0.075185,
                                                    'sadness': 0.648705}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.412325}}},
  'text': 'Going to merge my 2 instagram accounts'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.067931,
                                                    'disgust': 0.084504,
                                                    'fear': 0.290035,
                                                    'joy': 0.343112,
                                                    'sadness': 0.098555}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.266938}}},
  'text': 'There is an event next week'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.187381,
                                                    'disgust': 0.040689,
                                                    'fear': 0.249642,
                                                    'joy': 0.314062,
                                                    'sadness': 0.113379}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'neutral', 'score': 0.0}}},
  'text': 'Apple released a new computer'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.007699,
                                                    'disgust': 0.004617,
                                                    'fear': 0.016677,
                                                    'joy': 0.944894,
                                                    'sadness': 0.00247}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.85787}}},
  'text': 'The new Tesla is amazing!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.16746,
                                                    'disgust': 0.143381,
                                                    'fear': 0.164356,
                                                    'joy': 0.175009,
                                                    'sadness': 0.319412}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'neutral', 'score': 0.0}}},
  'text': 'My jacket is huge'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.051214,
                                                    'disgust': 0.012208,
                                                    'fear': 0.113114,
                                                    'joy': 0.539068,
                                                    'sadness': 0.133119}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.620715}}},
  'text': 'Just got a new desktop background'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.168098,
                                                    'disgust': 0.147999,
                                                    'fear': 0.097371,
                                                    'joy': 0.434485,
                                                    'sadness': 0.056161}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.516566}}},
  'text': 'That is some high quality paper'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.038282,
                                                    'disgust': 0.09916,
                                                    'fear': 0.083089,
                                                    'joy': 0.503515,
                                                    'sadness': 0.134467}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.401609}}},
  'text': 'Just about to start spring cleaning'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.02087,
                                                    'disgust': 0.030995,
                                                    'fear': 0.066247,
                                                    'joy': 0.789627,
                                                    'sadness': 0.012753}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.739931}}},
  'text': 'Just went to a great party!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.059593,
                                                    'disgust': 0.013466,
                                                    'fear': 0.036315,
                                                    'joy': 0.783547,
                                                    'sadness': 0.026481}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.811099}}},
  'text': 'Loving my new car!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.027968,
                                                    'disgust': 0.01122,
                                                    'fear': 0.02311,
                                                    'joy': 0.824058,
                                                    'sadness': 0.038521}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.815734}}},
  'text': 'I love the new Mercedes!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.072341,
                                                    'disgust': 0.059063,
                                                    'fear': 0.571572,
                                                    'joy': 0.011251,
                                                    'sadness': 0.38033}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'neutral', 'score': 0.0}}},
  'text': 'Oh yeah, I need a Tesla!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.001735,
                                                    'disgust': 0.002479,
                                                    'fear': 0.007943,
                                                    'joy': 0.967091,
                                                    'sadness': 0.005055}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.843149}}},
  'text': 'Happy Birthday!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.103205,
                                                    'disgust': 0.204409,
                                                    'fear': 0.159448,
                                                    'joy': 0.419142,
                                                    'sadness': 0.020889}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.461215}}},
  'text': 'Just won an award!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.061806,
                                                    'disgust': 0.020134,
                                                    'fear': 0.047735,
                                                    'joy': 0.643949,
                                                    'sadness': 0.096797}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.643158}}},
  'text': 'God, I love waking up in Silicon Valley'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.084915,
                                                    'disgust': 0.065899,
                                                    'fear': 0.241716,
                                                    'joy': 0.242638,
                                                    'sadness': 0.264874}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.497642}}},
  'text': "Think I'm going to go to the beach today, who's coming?"},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.01775,
                                                    'disgust': 0.036592,
                                                    'fear': 0.129377,
                                                    'joy': 0.641268,
                                                    'sadness': 0.04861}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.687642}}},
  'text': 'My dog is looking so cute today'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.031929,
                                                    'disgust': 0.025339,
                                                    'fear': 0.287489,
                                                    'joy': 0.489363,
                                                    'sadness': 0.023042}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'positive',
                                          'score': 0.594635}}},
  'text': 'Went out on a first date with my new girlfriend, was nervous, but '
          'it went great!'},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.154395,
                                                    'disgust': 0.113292,
                                                    'fear': 0.054378,
                                                    'joy': 0.079304,
                                                    'sadness': 0.609713}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'negative',
                                          'score': -0.848388}}},
  'text': "Just tried the new Starbucks drink, I can't even"},
 {'analysis': {'emotion': {'document': {'emotion': {'anger': 0.174968,
                                                    'disgust': 0.11618,
                                                    'fear': 0.152964,
                                                    'joy': 0.178625,
                                                    'sadness': 0.340056}}},
               'language': 'en',
               'sentiment': {'document': {'label': 'neutral', 'score': 0.0}}},
  'text': 'Just got my sobriety coin'}]

